apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sl-orderer4
  namespace: sl-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: sl-orderer4
  chart:
    git: git@github.com:lakshyakumar/blockchain-automation-framework.git
    ref: test2
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: sl-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer4
      loglevel: info
      localmspid: slMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: slsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: sl-net-auth
      secretprefix: secret/crypto/ordererOrganizations/sl-net/orderers/orderer4.sl-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com

    genesis: |-
      CiIaIJ5xLViFeaO8yZSXQXwSi3BVE9MRYSXwm3XTzKp9q3UREp5QCptQCphQCngKWggBEAEaBgih
      npqABiIKc3lzY2hhbm5lbCpANGNmYjZkMjUyNzc4YTk4Njc0ZGJhYWM3NDQ3ZmEyNDJjMTI4OTk5
      ODVlMjlmYTQ5N2I2ZjUyYzNlZjZmOGU4YhIaEhgKimGzcnr0T9gcEy3bGrLXXK07lxPr+5ASm08K
      mE8SlU8S2ykKB09yZGVyZXISzykSqxUKBXNsTVNQEqEVGtETCgNNU1ASyRMSvhMSuxMKBXNsTVNQ
      Es0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0ekNDQVltZ0F3SUJBZ0lKQVA0NHpw
      OXV0cldjTUFvR0NDcUdTTTQ5QkFNQ01GVXhDekFKQmdOVkJBWVQKQWtkQ01ROHdEUVlEVlFRSURB
      Wk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SApUM0prWlhKbGNq
      RVNNQkFHQTFVRUF3d0pZMkV1YzJ3dGJtVjBNQjRYRFRJeE1ERXhPVEEzTkRBd01Gb1hEVEl6Ck1U
      RXdPVEEzTkRBd01Gb3dWVEVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEcKQTFVRUJ3d0dURzl1Wkc5dU1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SSXdFQVlEVlFR
      RERBbGpZUzV6YkMxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRhRUpY
      c0NBd3ovS1Y2TjFJU2JrMjBzS0lOCmZpZ1l5N2ZJT0hGaGt0eWtRSHRHSmwraGJJdTdJVi8rMzBX
      S05MSkdkaVQ0dUl3NGhYOWJXcFpPWm1mSW8wSXcKUURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVYnZiaQpjRkJycVhNUC9vcStKSnNXSGo4
      UzBWVXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTm9uWE1hTmE5SlkzSEtUCmFFT1pteWMvTTQw
      dFFidmFCSmtYVDd5b0Y3QnVBaUI2d3FxMExPTUc3aEROejNtQXorZWxZSHh3RjdZSDZ1WHoKeUp4
      b2I2bnEvZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIoEILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUN5VENDQW0rZ0F3SUJBZ0lVWTN1MGVUMEI0cWhFM1Q3cXB1YXA4WGNreFJV
      d0NnWUlLb1pJemowRUF3SXcKVlRFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUkl3RUFZ
      RFZRUUREQWxqWVM1emJDMXVaWFF3SGhjTk1qRXdNVEU1Ck1EYzBNekF3V2hjTk1qSXdNVEU1TURj
      ME9EQXdXakJrTVFzd0NRWURWUVFHRXdKSFFqRWJNQmtHQTFVRUJ4TVMKTlRFdU5UQXZMVEF1TVRN
      dlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4d0RRWURWUVFMRXdaagpiR2xsYm5R
      eEZUQVRCZ05WQkFNTURFRmtiV2x1UUhOc0xXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5
      CkF3RUhBMElBQkUwOUZtclQvRjBNMW5HRW9oTVhwVW1qNE1TL1dOZEQ4L1J5TFZZREJ4aExJc1pP
      ekl4bmF3aVMKcG5IN3A5NVhLVWMwMHFudGdEQmgyaXQ4VTJFaUpIR2pnZ0VNTUlJQkNEQU9CZ05W
      SFE4QkFmOEVCQU1DQjRBdwpEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdRVWF3M3U5Lytr
      Y3NDck5pdmJKeTYrdS9QTEFyc3dId1lEClZSMGpCQmd3Rm9BVWJ2YmljRkJycVhNUC9vcStKSnNX
      SGo4UzBWVXdKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXYKYkhNdE9EVmlPV0kwTldNNU9TMXpkREpq
      Y3pDQmdRWUlLZ01FQlFZSENBRUVkWHNpWVhSMGNuTWlPbnNpWVdKaApZeTVwYm1sMElqb2lkSEox
      WlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pCklpd2lhR1l1
      Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMyd3RibVYwSWl3aWFHWXVWSGx3WlNJNkltTnMK
      YVdWdWRDSjlmVEFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBdWRJY2ZVeWRkb1p3TTdRTzhMR3pX
      RjVwRHEyTgpqU1dtRmhrS25sSklJZlFDSUNKTk1WKzNacXlwZTNZQTE2SWpKOUtWeTh4Um92a0pZ
      ZitzTkFseXFFTHQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2Ss0F
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0ekNDQVltZ0F3SUJBZ0lKQVA0NHpwOXV0
      cldjTUFvR0NDcUdTTTQ5QkFNQ01GVXhDekFKQmdOVkJBWVQKQWtkQ01ROHdEUVlEVlFRSURBWk1i
      MjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SApUM0prWlhKbGNqRVNN
      QkFHQTFVRUF3d0pZMkV1YzJ3dGJtVjBNQjRYRFRJeE1ERXhPVEEzTkRBd01Gb1hEVEl6Ck1URXdP
      VEEzTkRBd01Gb3dWVEVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEcKQTFVRUJ3d0dURzl1Wkc5dU1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SSXdFQVlEVlFRRERB
      bGpZUzV6YkMxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRhRUpYc0NB
      d3ovS1Y2TjFJU2JrMjBzS0lOCmZpZ1l5N2ZJT0hGaGt0eWtRSHRHSmwraGJJdTdJVi8rMzBXS05M
      SkdkaVQ0dUl3NGhYOWJXcFpPWm1mSW8wSXcKUURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0Ex
      VWREd0VCL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVYnZiaQpjRkJycVhNUC9vcStKSnNXSGo4UzBW
      VXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTm9uWE1hTmE5SlkzSEtUCmFFT1pteWMvTTQwdFFi
      dmFCSmtYVDd5b0Y3QnVBaUI2d3FxMExPTUc3aEROejNtQXorZWxZSHh3RjdZSDZ1WHoKeUp4b2I2
      bnEvZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiLgoHV3JpdGVycxIjEhkI
      ARIVEggSBggBEgIIABoJEgcKBXNsTVNQGgZBZG1pbnMiLwoGQWRtaW5zEiUSGwgBEhcSCBIGCAES
      AggAGgsSCQoFc2xNU1AQARoGQWRtaW5zIjIKC0VuZG9yc2VtZW50EiMSGQgBEhUSCBIGCAESAggA
      GgkSBwoFc2xNU1AaBkFkbWlucyIuCgdSZWFkZXJzEiMSGQgBEhUSCBIGCAESAggAGgkSBwoFc2xN
      U1AaBkFkbWlucyoGQWRtaW5zGvMRCg1Db25zZW5zdXNUeXBlEuEREtYRCghldGNkcmFmdBLJEQqy
      EQozb3JkZXJlcjQuaGYuZGV2Mi5hd3MuYmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtB
      GroILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4VENDQXBpZ0F3SUJBZ0lVRERzdTAz
      NHlybkIwRXdIYzhUVXcvS0k5bE5Rd0NnWUlLb1pJemowRUF3SXcKVlRFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUkl3RUFZRFZRUUREQWxqWVM1emJDMXVaWFF3SGhjTk1qRXdNVEU1Ck1E
      YzBOREF3V2hjTk1qSXdNVEU1TURjME9UQXdXakJsTVFzd0NRWURWUVFHRXdKSFFqRWJNQmtHQTFV
      RUJ4TVMKTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVEw
      d0N3WURWUVFMRXdSdwpaV1Z5TVJnd0ZnWURWUVFERXc5dmNtUmxjbVZ5TkM1emJDMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPClBRTUJCd05DQUFUS1cwL0VYNUpJS2tDRlNKTEVIUWNrVU9H
      Mzg5Zi9STkVYL3VtanRKbmF6L01IUWRQaEs5R0UKVUdnajRJbDJXUll2ODRUSXBVZlQxQmwyWHFY
      YVZNRHJvNElCTkRDQ0FUQXdEZ1lEVlIwUEFRSC9CQVFEQWdPbwpNQjBHQTFVZEpRUVdNQlFHQ0Nz
      R0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHCkExVWREZ1FXQkJS
      aENHRkN0eE5ldWtzVlUzcGUzOHA0aWFOY29qQWZCZ05WSFNNRUdEQVdnQlJ1OXVKd1VHdXAKY3cv
      K2lyNGtteFllUHhMUlZUQlBCZ05WSFJFRVNEQkdnZzl2Y21SbGNtVnlOQzV6YkMxdVpYU0NNMjl5
      WkdWeQpaWEkwTG1obUxtUmxkakl1WVhkekxtSnNiMk5yWTJoaGFXNWpiRzkxWkhCdll5MWtaWFps
      Ykc5d0xtTnZiVEJnCkJnZ3FBd1FGQmdjSUFRUlVleUpoZEhSeWN5STZleUpvWmk1QlptWnBiR2xo
      ZEdsdmJpSTZJaUlzSW1obUxrVnUKY205c2JHMWxiblJKUkNJNkltOXlaR1Z5WlhJMExuTnNMVzVs
      ZENJc0ltaG1MbFI1Y0dVaU9pSndaV1Z5SW4xOQpNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRitq
      dWpMR210Yk5iOFZxaHJiaXVpUkFySE9EOUd4T21XNnZDUVNmCmhWL2xBaUEvS3ZaR2JpemNSYXJu
      bDRwNE5IMGQ4aW56UTFma2ZLc0dUU1FSdGV6NFV3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
      LQoiuggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhUQ0NBcGlnQXdJQkFnSVVERHN1
      MDM0eXJuQjBFd0hjOFRVdy9LSTlsTlF3Q2dZSUtvWkl6ajBFQXdJdwpWVEVMTUFrR0ExVUVCaE1D
      UjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lE
      VlFRS0RBZFBjbVJsY21WeU1SSXdFQVlEVlFRRERBbGpZUzV6YkMxdVpYUXdIaGNOTWpFd01URTUK
      TURjME5EQXdXaGNOTWpJd01URTVNRGMwT1RBd1dqQmxNUXN3Q1FZRFZRUUdFd0pIUWpFYk1Ca0dB
      MVVFQnhNUwpOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNtVnlN
      UTB3Q3dZRFZRUUxFd1J3ClpXVnlNUmd3RmdZRFZRUURFdzl2Y21SbGNtVnlOQzV6YkMxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak8KUFFNQkJ3TkNBQVRLVzAvRVg1SklLa0NGU0pMRUhRY2tV
      T0czODlmL1JORVgvdW1qdEpuYXovTUhRZFBoSzlHRQpVR2dqNElsMldSWXY4NFRJcFVmVDFCbDJY
      cVhhVk1Ecm80SUJORENDQVRBd0RnWURWUjBQQVFIL0JBUURBZ09vCk1CMEdBMVVkSlFRV01CUUdD
      Q3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEcKQTFVZERnUVdC
      QlJoQ0dGQ3R4TmV1a3NWVTNwZTM4cDRpYU5jb2pBZkJnTlZIU01FR0RBV2dCUnU5dUp3VUd1cApj
      dy8raXI0a214WWVQeExSVlRCUEJnTlZIUkVFU0RCR2dnOXZjbVJsY21WeU5DNXpiQzF1WlhTQ00y
      OXlaR1Z5ClpYSTBMbWhtTG1SbGRqSXVZWGR6TG1Kc2IyTnJZMmhoYVc1amJHOTFaSEJ2WXkxa1pY
      WmxiRzl3TG1OdmJUQmcKQmdncUF3UUZCZ2NJQVFSVWV5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acGJH
      bGhkR2x2YmlJNklpSXNJbWhtTGtWdQpjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEkwTG5Oc0xX
      NWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5Ck1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lG
      K2p1akxHbXRiTmI4VnFocmJpdWlSQXJIT0Q5R3hPbVc2dkNRU2YKaFYvbEFpQS9LdlpHYml6Y1Jh
      cm5sNHA0TkgwZDhpbnpRMWZrZktzR1RTUVJ0ZXo0VXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0t
      LS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEY
      gIBAGgZBZG1pbnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVz
      dHJpY3Rpb25zEggaBkFkbWlucxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5z
      IiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZB
      ZG1pbnMQAhoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxLYIgoLQ29uc29y
      dGl1bXMSyCIS/SEKFVN1cHBseUNoYWluQ29uc29ydGl1bRLjIRKFIQoFY2xNU1AS+yAaqx8KA01T
      UBKjHxKYHxKVHwoFY2xNU1ASzQUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjR6Q0NB
      WW1nQXdJQkFnSUpBTDk5M01ZcDZENHNNQW9HQ0NxR1NNNDlCQU1DTUZVeEN6QUpCZ05WQkFZVApB
      a2RDTVE4d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0Ex
      VUVDZ3dIClEyRnljbWxsY2pFU01CQUdBMVVFQXd3SlkyRXVZMnd0Ym1WME1CNFhEVEl4TURFeE9U
      QTNOREF4T0ZvWERUSXoKTVRFd09UQTNOREF4T0Zvd1ZURUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwRwpBMVVFQnd3R1RHOXVaRzl1TVJBd0RnWURWUVFLREFkRFlY
      SnlhV1Z5TVJJd0VBWURWUVFEREFsallTNWpiQzF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUXBOT0ZIUDVSVlJVd0tBZ3o3VGtaSkZlTWIKS2l4dy8zeGluem5YTHkvL3Mr
      WTBJSmRJZUdTYTgwZEgwbmFsck9CWG9DdHVydnpSdktHYmhKUFh6L1VybzBJdwpRREFQQmdOVkhS
      TUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVwbjllClUv
      cmRsOEhHQnlGMGh1N0Vpa1JZK3ZRd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ2VWZW41RWtGbmRB
      NU1WWnAKNzdhVDVTSEk5SUxKZmhMSzNQYmtKV2JBM25nQ0lRQ25lbSs0Ty93aHVleEFpMEQ3Z0FM
      Mjhub2pldzdPU01nbQo4bjl6UDRCZnB3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoioggt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzN6Q0NBb2FnQXdJQkFnSVVPK2R1U2w1YTRw
      T1MvZTFKL0hraml3dkd6clV3Q2dZSUtvWkl6ajBFQXdJdwpWVEVMTUFrR0ExVUVCaE1DUjBJeER6
      QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RB
      ZERZWEp5YVdWeU1SSXdFQVlEVlFRRERBbGpZUzVqYkMxdVpYUXdIaGNOTWpFd01URTUKTURjME5E
      QXdXaGNOTWpJd01URTVNRGMwT1RBd1dqQjBNUXN3Q1FZRFZRUUdFd0pIUWpFYk1Ca0dBMVVFQnhN
      UwpOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2REWVhKeWFXVnlNUjh3RFFZ
      RFZRUUxFd1pqCmJHbGxiblF3RGdZRFZRUUxFd2REWVhKeWFXVnlNUlV3RXdZRFZRUUREQXhCWkcx
      cGJrQmpiQzF1WlhRd1dUQVQKQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUmw4RlpFOG1Y
      WTAreVpYUWZEVXVDKzR1Q1JMWUZ4d2RUWQp2YTFRbitPUVppK0lJN045bnhxem1iMGtWSC9BK2Zp
      b21mVXg2QkhVTkFNaWJUR2xLa2M3bzRJQkV6Q0NBUTh3CkRnWURWUjBQQVFIL0JBUURBZ2VBTUF3
      R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGT0Z4NTFpRFVyQ00KVEQwbUIrRE5VaWRuWWxv
      cE1COEdBMVVkSXdRWU1CYUFGS1ovWGxQNjNaZkJ4Z2NoZElidXhJcEVXUHIwTUNRRwpBMVVkRVFR
      ZE1CdUNHV05oTFhSdmIyeHpMVGcxWWpsaU5EVmpPVGt0WTI0NU5Yb3dnWWdHQ0NvREJBVUdCd2dC
      CkJIeDdJbUYwZEhKeklqcDdJbUZpWVdNdWFXNXBkQ0k2SW5SeWRXVWlMQ0poWkcxcGJpSTZJblJ5
      ZFdVaUxDSm8KWmk1QlptWnBiR2xoZEdsdmJpSTZJa05oY25KcFpYSWlMQ0pvWmk1RmJuSnZiR3h0
      Wlc1MFNVUWlPaUpCWkcxcApia0JqYkMxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWTJ4cFpXNTBJbjE5
      TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDCklGTW5nS2NJbVh0RTVFeVpRN0I3YWtIZ0pRU3YrYlBU
      ZEcvVTE0dm10bnBQQWlCb2ZLb1lrSGpzVzhyaFhCYmwKbnplbDROL2IwVWhzSy9BVlpBUFA5bCtM
      SHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKzQUtLS0tLUJF
      R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjR6Q0NBWW1nQXdJQkFnSUpBTDk5M01ZcDZENHNNQW9H
      Q0NxR1NNNDlCQU1DTUZVeEN6QUpCZ05WQkFZVApBa2RDTVE4d0RRWURWUVFJREFaTWIyNWtiMjR4
      RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIClEyRnljbWxsY2pFU01CQUdBMVVF
      QXd3SlkyRXVZMnd0Ym1WME1CNFhEVEl4TURFeE9UQTNOREF4T0ZvWERUSXoKTVRFd09UQTNOREF4
      T0Zvd1ZURUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwRwpBMVVF
      Qnd3R1RHOXVaRzl1TVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJJd0VBWURWUVFEREFsallTNWpi
      QzF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUXBOT0ZIUDVSVlJVd0tB
      Z3o3VGtaSkZlTWIKS2l4dy8zeGluem5YTHkvL3MrWTBJSmRJZUdTYTgwZEgwbmFsck9CWG9DdHVy
      dnpSdktHYmhKUFh6L1VybzBJdwpRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIv
      d1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVwbjllClUvcmRsOEhHQnlGMGh1N0Vpa1JZK3ZRd0NnWUlL
      b1pJemowRUF3SURTQUF3UlFJZ2VWZW41RWtGbmRBNU1WWnAKNzdhVDVTSEk5SUxKZmhMSzNQYmtK
      V2JBM25nQ0lRQ25lbSs0Ty93aHVleEFpMEQ3Z0FMMjhub2pldzdPU01nbQo4bjl6UDRCZnB3PT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpatgsIARLYBQrNBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCNHpDQ0FZbWdBd0lCQWdJSkFMOTkzTVlwNkQ0c01Bb0dDQ3FHU000OUJBTUNN
      RlV4Q3pBSkJnTlZCQVlUCkFrZENNUTh3RFFZRFZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01C
      a3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0gKUTJGeWNtbGxjakVTTUJBR0ExVUVBd3dKWTJFdVkyd3Ri
      bVYwTUI0WERUSXhNREV4T1RBM05EQXhPRm9YRFRJegpNVEV3T1RBM05EQXhPRm93VlRFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHCkExVUVCd3dHVEc5dVpHOXVN
      UkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUkl3RUFZRFZRUUREQWxqWVM1amJDMXUKWlhRd1dUQVRC
      Z2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRcE5PRkhQNVJWUlV3S0FnejdUa1pKRmVNYgpL
      aXh3LzN4aW56blhMeS8vcytZMElKZEllR1NhODBkSDBuYWxyT0JYb0N0dXJ2elJ2S0diaEpQWHov
      VXJvMEl3ClFEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCcGpBZEJn
      TlZIUTRFRmdRVXBuOWUKVS9yZGw4SEdCeUYwaHU3RWlrUlkrdlF3Q2dZSUtvWkl6ajBFQXdJRFNB
      QXdSUUlnZVZlbjVFa0ZuZEE1TVZacAo3N2FUNVNISTlJTEpmaExLM1Bia0pXYkEzbmdDSVFDbmVt
      KzRPL3dodWV4QWkwRDdnQUwyOG5vamV3N09TTWdtCjhuOXpQNEJmcHc9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tChIGY2xpZW50GtYFCs0FLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SUI0ekNDQVltZ0F3SUJBZ0lKQUw5OTNNWXA2RDRzTUFvR0NDcUdTTTQ5QkFNQ01GVXhDekFKQmdO
      VkJBWVQKQWtkQ01ROHdEUVlEVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpF
      UU1BNEdBMVVFQ2d3SApRMkZ5Y21sbGNqRVNNQkFHQTFVRUF3d0pZMkV1WTJ3dGJtVjBNQjRYRFRJ
      eE1ERXhPVEEzTkRBeE9Gb1hEVEl6Ck1URXdPVEEzTkRBeE9Gb3dWVEVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEcKQTFVRUJ3d0dURzl1Wkc5dU1SQXdEZ1lEVlFR
      S0RBZERZWEp5YVdWeU1SSXdFQVlEVlFRRERBbGpZUzVqYkMxdQpaWFF3V1RBVEJnY3Foa2pPUFFJ
      QkJnZ3Foa2pPUFFNQkJ3TkNBQVFwTk9GSFA1UlZSVXdLQWd6N1RrWkpGZU1iCktpeHcvM3hpbnpu
      WEx5Ly9zK1kwSUpkSWVHU2E4MGRIMG5hbHJPQlhvQ3R1cnZ6UnZLR2JoSlBYei9Vcm8wSXcKUURB
      UEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FV
      cG45ZQpVL3JkbDhIR0J5RjBodTdFaWtSWSt2UXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWdlVmVu
      NUVrRm5kQTVNVlpwCjc3YVQ1U0hJOUlMSmZoTEszUGJrSldiQTNuZ0NJUUNuZW0rNE8vd2h1ZXhB
      aTBEN2dBTDI4bm9qZXc3T1NNZ20KOG45elA0QmZwdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KEgRwZWVyGgZBZG1pbnMiLwoGQWRtaW5zEiUSGwgBEhcSCBIGCAESAggAGgsSCQoFY2xNU1AQ
      ARoGQWRtaW5zIjIKC0VuZG9yc2VtZW50EiMSGQgBEhUSCBIGCAESAggAGgkSBwoFY2xNU1AaBkFk
      bWlucyIuCgdSZWFkZXJzEiMSGQgBEhUSCBIGCAESAggAGgkSBwoFY2xNU1AaBkFkbWlucyIuCgdX
      cml0ZXJzEiMSGQgBEhUSCBIGCAESAggAGgkSBwoFY2xNU1AaBkFkbWlucyoGQWRtaW5zGkAKFUNo
      YW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRt
      aW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFu
      bmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxn
      b3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQ
      EgYI/////w8aBkFkbWlucxppChBPcmRlcmVyQWRkcmVzc2VzElUSOgo4b3JkZXJlcjQuaGYuZGV2
      Mi5hd3MuYmxvY2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tOjg0NDMaFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHV3JpdGVy
      cxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZB
      ZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoA
      CgAKAAoACgA=
