apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-wl-peer0
  namespace: wl-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: joinchannel-peer0-join-allchannel-wl-peer0
  chart:
    git: git@github.com:lakshyakumar/blockchain-automation-framework.git
    ref: test2
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: wl-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.wl-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: wlMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: wl-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/wl-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/wl-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer4.hf.dev2.aws.blockchaincloudpoc-develop.com:8443

