apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-cl
  namespace: cl-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-cl
  chart:
    git: git@github.com:lakshyakumar/blockchain-automation-framework.git
    ref: test2
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: cl-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.cl-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: clMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: cl-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/cl-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/cl-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer4.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    anchorstx: |-
      CtQCChgKFggCGgYIrOKagAYiCmFsbGNoYW5uZWwStwIKtAIKCmFsbGNoYW5uZWwSXhJcCgtBcHBs
      aWNhdGlvbhJNCAESSQoFY2xNU1ASQBoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIA
      IgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAaxQESwgEKC0FwcGxpY2F0aW9uErIBCAESrQEK
      BWNsTVNQEqMBCAEaVwoLQW5jaG9yUGVlcnMSSBI+CjwKN3BlZXIwLmNsLW5ldC5oZi5kZXYyLmF3
      cy5ibG9ja2NoYWluY2xvdWRwb2MtZGV2ZWxvcC5jb20Q+0EaBkFkbWlucxoHCgNNU1ASACIKCgZB
      ZG1pbnMSACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAqBkFkbWlu
      cw==

