apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: instantiate-cl-allchannel-supplychain1
  namespace: cl-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: instantiate-cl-allchannel-supplychain1
  chart:
    git: git@github.com:lakshyakumar/blockchain-automation-framework.git
    ref: test2
    path: platforms/hyperledger-fabric/charts/instantiate_chaincode
  values:
    metadata:
      namespace: cl-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.cl-net:7051
      localmspid: clMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: cl-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/cl-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/cl-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer4.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:1.4.4
      name: supplychain
      lang: golang
      version: 1
      instantiationarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel