apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturerlmanufacturerlibft
  namespace: manufacturerl-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturerlmanufacturerlibft
  chart:
    git: git@github.com:lakshyakumar/blockchain-automation-framework.git
    ref: test2
    path: platforms/hyperledger-besu/charts/node_orion 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://cb5e1298c4e061e2ed3e0e9fbf0db5499fc052b44e55d3fa85cee5555fe7f17dddea122f00469e3f1a7864546a4b9fa57009a7da819ec5e3e5b8eb7b9e1a9e44@52.212.240.252:15050"
      - "enode://4fda4044713ed17d13566bdb492b377f68d0ee90628ca198d329ed7f4724596dc5bf8238babd01e7be8752b2404e85439c4947f08537510be579dc653c26553f@52.212.240.252:15060"
      - "enode://00ebe435afda76eeb6ce5da5b9c732615ae5d6fb956e1232c5edc451a2e6a9fbb74c62bb68e71a28fab30649a4ff8c5fca4556dfd25342664ee9fdf8eadc33c7@52.212.240.252:15070"
      - "enode://b39f648801ce382f8ce16ac9660e751c67ab2b898c31c4df9e9ec683569bd5820c5f87ade4c6d791d5cba2302593f34d8aea4da24b572f77416ffb7122073aed@52.212.240.252:15080"
      - "enode://fb0280e586d77e5b3ea05f2dcf1ae4f3df4885d7dca84e7b3cf23e9c637d35b74c8d514a20d0dd1a1a9694aab1d3707d41ba890e743f3fcbf7dda10ba2894a79@52.212.240.252:15010"
      - "enode://3419d3ac990bfaa08226c175e5a4ed8e37416bc479a1ff81409d389fd669bbc15d5bcaf541c2cacad5032c98ee13bdd9d96a83b52d0ce5ae702a81698267b1a1@52.212.240.252:15020"
      - "enode://058720ea57a3d99016629c80f2d6bc5f4998b31eca594322cf2b0d79f6d524fbb9f5395b1606b5af0b501b5c591c197a8c018a6c5588794d8f59a76d9fdab1a4@52.212.240.252:15030"
      - "enode://2ff9a523fce7eee497439aa5cbff0f6b862d53e69dfb6588bca6d6741d65a31da77f15cbaf32b9059ac88a82833e396aafa836999aebfd6726b01b3fd688b8f7@52.212.240.252:15040"

    metadata:
      namespace: manufacturerl-bes
      labels:

    liveliness_check:
      enabled: false

    proxy:
      provider: ambassador
      external_url: manufacturerl.rc.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15020
      rpc: 15021
      tmport: 15023

    images:
      node: hyperledger/besu:1.4.4
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      orion: pegasyseng/orion:1.5.2

    node:
      name: manufacturerl
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=Zurich,C=CH
      mountPath: /etc/genesis
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    orion:
      name: orion
      tls: True
      confdir: /etc/config
      url: "https://manufacturerl.rc.dev2.aws.blockchaincloudpoc-develop.com"
      nodelist: "\"https://carrierl.rc.dev2.aws.blockchaincloudpoc-develop.com:15013\",\"https://storel.rc.dev2.aws.blockchaincloudpoc-develop.com:15033\",\"https://warehousel.rc.dev2.aws.blockchaincloudpoc-develop.com:15043\""
      trust: ca-or-tofu
      ports:
        nodeport: 8888
        clientport: 8080

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/manufacturerl-bes/crypto/manufacturerl
      serviceaccountname: vault-auth
      keyname: data
      oriondir: orion
      tlsdir: tls
      role: vault-role
      authpath: besumanufacturerl

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDFlYzcwZWRmOWY0NmQzYzRhNWFmOGJjOTAwMmQ5Mzk4YWI0OTllZDQ5NGI3OGIzMTIwODc2ZmU2ODIyYjNlNDg1NTEwOTRjYjc0ZDQ2NzEyZjE5NGQ5MjkyNjhjZDQwZmY2YTA3OGQwYjE1MTI3MTgzZWQ2M2ZkYmE1OWQ5NDFlOTYwYmI3MzlhMmQ5NjkxYjM1OTUyNmEzZjQxMzQyYTVjYWFlMTc4MDg0MDAwMDAwMDBjMCIKfQ==
