apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wl-frontend
  namespace: wl-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/frontend
    git: "git@github.com:lakshyakumar/blockchain-automation-framework.git"
    ref: "test2"
  releaseName: wlfabric-frontend
  values:
    nodeName: wl-frontend
    metadata:
      namespace: wl-net
    replicaCount: 1
    frontend:
      serviceType: ClusterIP
      nodePorts:
        port: 8080
        targetPort: 80
      image: index.docker.io/hyperledgerlabs/supplychain_frontend:latest
      pullPolicy: Always
      pullSecrets: regcred
      env:
        webserver: https://wlapi.hf.dev2.aws.blockchaincloudpoc-develop.com
    deployment:
      annotations: {}
    proxy:
      provider: haproxy
      peer_name: wl
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
      ambassador_secret: peer0-wl-net-ambassador-certs
